## Numpy
NumPy (Numeric Python) là một thư viện toán học phổ biến và mạnh mẽ của Python. Cho phép làm việc hiệu quả trên các cấu trúc dữ liệu thường được dùng trong Machine Learning: vector, ma trận và mảng, đặc biệt với những mảng nhiều chiều (tensors) với tốc độ xử lý nhanh hơn nhiều lần khi chỉ sử dụng “core Python” đơn thuần.

In [1]:
import numpy as np

## Mảng 
Chúng ta có thể khởi tạo mảng numpy từ list các python lồng nhau và truy cập bằng cách sử dụng dấu ngoặc vuông

In [3]:
a = np.array([1,2,3]) # khởi tạo mảng 
print(type(a)) # output: numpy.ndarray
print(a.shape) # output: "(3,)"
a[0] = 5 # thay đổi giá trị tại phần tử đầu tiên
print(a)

<class 'numpy.ndarray'>
(3,)
[5 2 3]


Numpy cung cấp nhiều hàm khởi tạo mảng

In [4]:
a = np.zeros((2,2)) # khởi tạo mảng 2 chiều với giá trị 0
print(a)

[[0. 0.]
 [0. 0.]]


In [5]:
b = np.ones((1,2)) # khởi tạo mảng 2 chiều với giá trị 1
print(b)

[[1. 1.]]


In [6]:
c = np.full((2,2), 7) # khởi tạo mảng không đổi
print(c)

[[7 7]
 [7 7]]


In [7]:
d = np.eye(2) # khởi tạo ma trận đơn vị 
print(d)

[[1. 0.]
 [0. 1.]]


In [8]:
e = np.random.random((2,2)) # tạo mảng với các giá trị bất kỳ
print(e) 

[[0.97326306 0.21411106]
 [0.29860191 0.68691855]]


## Array Indexing

In [9]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])


In [10]:
# Sử dụng phép cắt để lấy mảng con 
# lấy 2 hàng đầu tiên và 2 cột 2,3
b = a[:2, 1:3]

In [13]:
print(b)

[[2 3]
 [6 7]]


In [14]:
b[0, 0] = 77 

In [18]:
print(b)
print(a)
# ma trận b là ma trận con của a nên khi thay đổi giá trị tại vị trí của ma trận b
# ma trận a cũng thay đổi

[[77  3]
 [ 6  7]]
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. 

In [20]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


## Array math
Các hàm toán học cơ bản hoạt động theo từng phần tử trên mảng và có sẵn dưới dạng nạp chồng toán tử và dưới dạng các hàm trong mô-đun numpy: 

In [7]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [9]:
print(x)

[[1. 2.]
 [3. 4.]]


In [8]:
# chuyển vị ma trận
print(x.T)

[[1. 3.]
 [2. 4.]]


In [23]:
# phép cộng
print(x+y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [24]:
#phép trừ
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [25]:
# phép nhân
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [27]:
#phép chia
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [29]:
#phép căn bậc 2
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


/* là phép nhân từng phần tử, không phải phép nhân ma trận. Để nhân ma trận trong numpy, numpy sử dụng hàm dấu chấm (.) để tính các tích bên trong của vector, hoặc nhân vector với ma trận và ma trận với ma trận. 

In [30]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [31]:
# vector * vector
print(v.dot(w))
print(np.dot(v, w))

219
219


In [32]:
# ma trận * vecotr
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [4]:
x = [1,2,3]
y = [3,4,5]

In [33]:
# ma trận * ma trận
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


## Broadcasting
Broadcasting là một cơ chế mạnh mẽ cho phép numpy làm việc với các mảng có hình dạng khác nhau khi thực hiện các phép toán số học. Thông thường, chúng ta có một mảng nhỏ hơn và một mảng lớn hơn, và chúng ta muốn sử dụng mảng nhỏ hơn nhiều lần để thực hiện một số thao tác trên mảng lớn hơn.

In [39]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x) # tạo ma trận rỗng với kích thước tương tự như ma trận x

In [40]:
print(y)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [41]:
for i in range(4):
    y[i, :] = x[i, :] + v

In [42]:
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Nếu ma trận x có kích thước lớn, việc tính toán vòng lặp trong python có thể chậm. Lưu ý rằng việc thêm vector v vào mỗi hàng của ma trận x tương đương với việc tạo một ma trận vv bằng cách xếp chồng nhiều bản sao của v theo chiều dọc, sau đó thực hiện tính tổng theo từng phần tử của x và vv. 

In [43]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)  

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [44]:
y = x + vv  # Add x and vv elementwise
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [45]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
