## Numpy
NumPy (Numeric Python) là một thư viện toán học phổ biến và mạnh mẽ của Python. Cho phép làm việc hiệu quả trên các cấu trúc dữ liệu thường được dùng trong Machine Learning: vector, ma trận và mảng, đặc biệt với những mảng nhiều chiều (tensors) với tốc độ xử lý nhanh hơn nhiều lần khi chỉ sử dụng “core Python” đơn thuần.

In [1]:
import numpy as np

## Mảng 
Chúng ta có thể khởi tạo mảng numpy từ list các python lồng nhau và truy cập bằng cách sử dụng dấu ngoặc vuông

In [4]:
a = np.array([1,2,3]) # khởi tạo mảng 
print(type(a)) # output: numpy.ndarray
print(a.shape) # output: "(3,)"
a[0] = 5 # thay đổi giá trị tại phần tử đầu tiên
print(a)

<class 'numpy.ndarray'>
(3,)
[5 2 3]


Numpy cung cấp nhiều hàm khởi tạo mảng

In [5]:
a = np.zeros((2,2)) # khởi tạo mảng 2 chiều với giá trị 0
print(a)

[[0. 0.]
 [0. 0.]]


In [6]:
b = np.ones((1,2)) # khởi tạo mảng 2 chiều với giá trị 1
print(b)

[[1. 1.]]


In [7]:
c = np.full((2,2), 7) # khởi tạo mảng không đổi
print(c)

[[7 7]
 [7 7]]


In [8]:
d = np.eye(2) # khởi tạo ma trận đơn vị 
print(d)

[[1. 0.]
 [0. 1.]]


In [11]:
e = np.random.random((2,2)) # tạo mảng với các giá trị bất kỳ
print(e) 

[[0.0477286  0.27033684]
 [0.05275796 0.75910658]]
